// Copyright 2017 The go-github AUTHORS. All rights reserved.
//
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.
// Code generated by gen-accessors; DO NOT EDIT.
package force

// HasRecords checks if QueryResult has any Records.
func (q *QueryResult) HasRecords() bool {
	if q == nil || q.Records == nil {
		return false
	}
	if len(q.Records) == 0 {
		return false
	}
	return true
}

// GetFormFactor returns the FormFactor field if it's non-nil, zero value otherwise.
func (s *SObjectActionOverrideMetadata) GetFormFactor() string {
	if s == nil || s.FormFactor == nil {
		return ""
	}
	return *s.FormFactor
}

// GetIsAvailableInTouch returns the IsAvailableInTouch field if it's non-nil, zero value otherwise.
func (s *SObjectActionOverrideMetadata) GetIsAvailableInTouch() bool {
	if s == nil || s.IsAvailableInTouch == nil {
		return false
	}
	return *s.IsAvailableInTouch
}

// GetName returns the Name field if it's non-nil, zero value otherwise.
func (s *SObjectActionOverrideMetadata) GetName() string {
	if s == nil || s.Name == nil {
		return ""
	}
	return *s.Name
}

// GetPageID returns the PageID field if it's non-nil, zero value otherwise.
func (s *SObjectActionOverrideMetadata) GetPageID() string {
	if s == nil || s.PageID == nil {
		return ""
	}
	return *s.PageID
}

// GetURL returns the URL field if it's non-nil, zero value otherwise.
func (s *SObjectActionOverrideMetadata) GetURL() string {
	if s == nil || s.URL == nil {
		return ""
	}
	return *s.URL
}

// GetCascadeDelete returns the CascadeDelete field if it's non-nil, zero value otherwise.
func (s *SObjectChildRelationshipMetadata) GetCascadeDelete() bool {
	if s == nil || s.CascadeDelete == nil {
		return false
	}
	return *s.CascadeDelete
}

// GetChildSObject returns the ChildSObject field if it's non-nil, zero value otherwise.
func (s *SObjectChildRelationshipMetadata) GetChildSObject() string {
	if s == nil || s.ChildSObject == nil {
		return ""
	}
	return *s.ChildSObject
}

// GetDeprecatedAndHidden returns the DeprecatedAndHidden field if it's non-nil, zero value otherwise.
func (s *SObjectChildRelationshipMetadata) GetDeprecatedAndHidden() bool {
	if s == nil || s.DeprecatedAndHidden == nil {
		return false
	}
	return *s.DeprecatedAndHidden
}

// GetField returns the Field field if it's non-nil, zero value otherwise.
func (s *SObjectChildRelationshipMetadata) GetField() string {
	if s == nil || s.Field == nil {
		return ""
	}
	return *s.Field
}

// HasJunctionIdListNames checks if SObjectChildRelationshipMetadata has any JunctionIdListNames.
func (s *SObjectChildRelationshipMetadata) HasJunctionIdListNames() bool {
	if s == nil || s.JunctionIdListNames == nil {
		return false
	}
	if len(s.JunctionIdListNames) == 0 {
		return false
	}
	return true
}

// HasJunctionReferenceTo checks if SObjectChildRelationshipMetadata has any JunctionReferenceTo.
func (s *SObjectChildRelationshipMetadata) HasJunctionReferenceTo() bool {
	if s == nil || s.JunctionReferenceTo == nil {
		return false
	}
	if len(s.JunctionReferenceTo) == 0 {
		return false
	}
	return true
}

// GetRelationshipName returns the RelationshipName field if it's non-nil, zero value otherwise.
func (s *SObjectChildRelationshipMetadata) GetRelationshipName() string {
	if s == nil || s.RelationshipName == nil {
		return ""
	}
	return *s.RelationshipName
}

// GetRestrictedDelete returns the RestrictedDelete field if it's non-nil, zero value otherwise.
func (s *SObjectChildRelationshipMetadata) GetRestrictedDelete() bool {
	if s == nil || s.RestrictedDelete == nil {
		return false
	}
	return *s.RestrictedDelete
}

// HasControllingFields checks if SObjectFieldFilteredLookupInfoMetadata has any ControllingFields.
func (s *SObjectFieldFilteredLookupInfoMetadata) HasControllingFields() bool {
	if s == nil || s.ControllingFields == nil {
		return false
	}
	if len(s.ControllingFields) == 0 {
		return false
	}
	return true
}

// GetAggregatable returns the Aggregatable field if it's non-nil, zero value otherwise.
func (s *SObjectFieldMetadata) GetAggregatable() bool {
	if s == nil || s.Aggregatable == nil {
		return false
	}
	return *s.Aggregatable
}

// GetAutoNumber returns the AutoNumber field if it's non-nil, zero value otherwise.
func (s *SObjectFieldMetadata) GetAutoNumber() bool {
	if s == nil || s.AutoNumber == nil {
		return false
	}
	return *s.AutoNumber
}

// GetByteLength returns the ByteLength field if it's non-nil, zero value otherwise.
func (s *SObjectFieldMetadata) GetByteLength() int {
	if s == nil || s.ByteLength == nil {
		return 0
	}
	return *s.ByteLength
}

// GetCalculated returns the Calculated field if it's non-nil, zero value otherwise.
func (s *SObjectFieldMetadata) GetCalculated() bool {
	if s == nil || s.Calculated == nil {
		return false
	}
	return *s.Calculated
}

// GetCalculatedFormula returns the CalculatedFormula field if it's non-nil, zero value otherwise.
func (s *SObjectFieldMetadata) GetCalculatedFormula() string {
	if s == nil || s.CalculatedFormula == nil {
		return ""
	}
	return *s.CalculatedFormula
}

// GetCascadeDelete returns the CascadeDelete field if it's non-nil, zero value otherwise.
func (s *SObjectFieldMetadata) GetCascadeDelete() bool {
	if s == nil || s.CascadeDelete == nil {
		return false
	}
	return *s.CascadeDelete
}

// GetCaseSensitive returns the CaseSensitive field if it's non-nil, zero value otherwise.
func (s *SObjectFieldMetadata) GetCaseSensitive() bool {
	if s == nil || s.CaseSensitive == nil {
		return false
	}
	return *s.CaseSensitive
}

// GetControllerName returns the ControllerName field if it's non-nil, zero value otherwise.
func (s *SObjectFieldMetadata) GetControllerName() string {
	if s == nil || s.ControllerName == nil {
		return ""
	}
	return *s.ControllerName
}

// GetCreateable returns the Createable field if it's non-nil, zero value otherwise.
func (s *SObjectFieldMetadata) GetCreateable() bool {
	if s == nil || s.Createable == nil {
		return false
	}
	return *s.Createable
}

// GetCustom returns the Custom field if it's non-nil, zero value otherwise.
func (s *SObjectFieldMetadata) GetCustom() bool {
	if s == nil || s.Custom == nil {
		return false
	}
	return *s.Custom
}

// GetDefaultedOnCreate returns the DefaultedOnCreate field if it's non-nil, zero value otherwise.
func (s *SObjectFieldMetadata) GetDefaultedOnCreate() bool {
	if s == nil || s.DefaultedOnCreate == nil {
		return false
	}
	return *s.DefaultedOnCreate
}

// GetDefaultValueFormula returns the DefaultValueFormula field if it's non-nil, zero value otherwise.
func (s *SObjectFieldMetadata) GetDefaultValueFormula() string {
	if s == nil || s.DefaultValueFormula == nil {
		return ""
	}
	return *s.DefaultValueFormula
}

// GetDependentPicklist returns the DependentPicklist field if it's non-nil, zero value otherwise.
func (s *SObjectFieldMetadata) GetDependentPicklist() bool {
	if s == nil || s.DependentPicklist == nil {
		return false
	}
	return *s.DependentPicklist
}

// GetDeprecatedAndHidden returns the DeprecatedAndHidden field if it's non-nil, zero value otherwise.
func (s *SObjectFieldMetadata) GetDeprecatedAndHidden() bool {
	if s == nil || s.DeprecatedAndHidden == nil {
		return false
	}
	return *s.DeprecatedAndHidden
}

// GetDigits returns the Digits field if it's non-nil, zero value otherwise.
func (s *SObjectFieldMetadata) GetDigits() int {
	if s == nil || s.Digits == nil {
		return 0
	}
	return *s.Digits
}

// GetDisplayLocationInDecimal returns the DisplayLocationInDecimal field if it's non-nil, zero value otherwise.
func (s *SObjectFieldMetadata) GetDisplayLocationInDecimal() bool {
	if s == nil || s.DisplayLocationInDecimal == nil {
		return false
	}
	return *s.DisplayLocationInDecimal
}

// GetEncrypted returns the Encrypted field if it's non-nil, zero value otherwise.
func (s *SObjectFieldMetadata) GetEncrypted() bool {
	if s == nil || s.Encrypted == nil {
		return false
	}
	return *s.Encrypted
}

// GetExternalID returns the ExternalID field if it's non-nil, zero value otherwise.
func (s *SObjectFieldMetadata) GetExternalID() bool {
	if s == nil || s.ExternalID == nil {
		return false
	}
	return *s.ExternalID
}

// GetExtraTypeInfo returns the ExtraTypeInfo field if it's non-nil, zero value otherwise.
func (s *SObjectFieldMetadata) GetExtraTypeInfo() string {
	if s == nil || s.ExtraTypeInfo == nil {
		return ""
	}
	return *s.ExtraTypeInfo
}

// GetFilterable returns the Filterable field if it's non-nil, zero value otherwise.
func (s *SObjectFieldMetadata) GetFilterable() bool {
	if s == nil || s.Filterable == nil {
		return false
	}
	return *s.Filterable
}

// GetFilteredLookupInfo returns the FilteredLookupInfo field.
func (s *SObjectFieldMetadata) GetFilteredLookupInfo() *SObjectFieldFilteredLookupInfoMetadata {
	if s == nil {
		return nil
	}
	return s.FilteredLookupInfo
}

// GetGroupable returns the Groupable field if it's non-nil, zero value otherwise.
func (s *SObjectFieldMetadata) GetGroupable() bool {
	if s == nil || s.Groupable == nil {
		return false
	}
	return *s.Groupable
}

// GetHighScaleNumber returns the HighScaleNumber field if it's non-nil, zero value otherwise.
func (s *SObjectFieldMetadata) GetHighScaleNumber() bool {
	if s == nil || s.HighScaleNumber == nil {
		return false
	}
	return *s.HighScaleNumber
}

// GetHTMLFormatted returns the HTMLFormatted field if it's non-nil, zero value otherwise.
func (s *SObjectFieldMetadata) GetHTMLFormatted() bool {
	if s == nil || s.HTMLFormatted == nil {
		return false
	}
	return *s.HTMLFormatted
}

// GetIDLookup returns the IDLookup field if it's non-nil, zero value otherwise.
func (s *SObjectFieldMetadata) GetIDLookup() bool {
	if s == nil || s.IDLookup == nil {
		return false
	}
	return *s.IDLookup
}

// GetInlineHelpText returns the InlineHelpText field if it's non-nil, zero value otherwise.
func (s *SObjectFieldMetadata) GetInlineHelpText() string {
	if s == nil || s.InlineHelpText == nil {
		return ""
	}
	return *s.InlineHelpText
}

// GetLabel returns the Label field if it's non-nil, zero value otherwise.
func (s *SObjectFieldMetadata) GetLabel() string {
	if s == nil || s.Label == nil {
		return ""
	}
	return *s.Label
}

// GetLength returns the Length field if it's non-nil, zero value otherwise.
func (s *SObjectFieldMetadata) GetLength() int {
	if s == nil || s.Length == nil {
		return 0
	}
	return *s.Length
}

// GetMask returns the Mask field if it's non-nil, zero value otherwise.
func (s *SObjectFieldMetadata) GetMask() string {
	if s == nil || s.Mask == nil {
		return ""
	}
	return *s.Mask
}

// GetMaskType returns the MaskType field if it's non-nil, zero value otherwise.
func (s *SObjectFieldMetadata) GetMaskType() string {
	if s == nil || s.MaskType == nil {
		return ""
	}
	return *s.MaskType
}

// GetName returns the Name field if it's non-nil, zero value otherwise.
func (s *SObjectFieldMetadata) GetName() string {
	if s == nil || s.Name == nil {
		return ""
	}
	return *s.Name
}

// GetNameField returns the NameField field if it's non-nil, zero value otherwise.
func (s *SObjectFieldMetadata) GetNameField() bool {
	if s == nil || s.NameField == nil {
		return false
	}
	return *s.NameField
}

// GetNamePointing returns the NamePointing field if it's non-nil, zero value otherwise.
func (s *SObjectFieldMetadata) GetNamePointing() bool {
	if s == nil || s.NamePointing == nil {
		return false
	}
	return *s.NamePointing
}

// GetNillable returns the Nillable field if it's non-nil, zero value otherwise.
func (s *SObjectFieldMetadata) GetNillable() bool {
	if s == nil || s.Nillable == nil {
		return false
	}
	return *s.Nillable
}

// GetPermissionable returns the Permissionable field if it's non-nil, zero value otherwise.
func (s *SObjectFieldMetadata) GetPermissionable() bool {
	if s == nil || s.Permissionable == nil {
		return false
	}
	return *s.Permissionable
}

// HasPicklistValues checks if SObjectFieldMetadata has any PicklistValues.
func (s *SObjectFieldMetadata) HasPicklistValues() bool {
	if s == nil || s.PicklistValues == nil {
		return false
	}
	if len(s.PicklistValues) == 0 {
		return false
	}
	return true
}

// GetPrecision returns the Precision field if it's non-nil, zero value otherwise.
func (s *SObjectFieldMetadata) GetPrecision() int {
	if s == nil || s.Precision == nil {
		return 0
	}
	return *s.Precision
}

// GetQueryByDistance returns the QueryByDistance field if it's non-nil, zero value otherwise.
func (s *SObjectFieldMetadata) GetQueryByDistance() bool {
	if s == nil || s.QueryByDistance == nil {
		return false
	}
	return *s.QueryByDistance
}

// GetReferenceTargetField returns the ReferenceTargetField field if it's non-nil, zero value otherwise.
func (s *SObjectFieldMetadata) GetReferenceTargetField() string {
	if s == nil || s.ReferenceTargetField == nil {
		return ""
	}
	return *s.ReferenceTargetField
}

// HasReferenceTo checks if SObjectFieldMetadata has any ReferenceTo.
func (s *SObjectFieldMetadata) HasReferenceTo() bool {
	if s == nil || s.ReferenceTo == nil {
		return false
	}
	if len(s.ReferenceTo) == 0 {
		return false
	}
	return true
}

// GetRelationshipName returns the RelationshipName field if it's non-nil, zero value otherwise.
func (s *SObjectFieldMetadata) GetRelationshipName() string {
	if s == nil || s.RelationshipName == nil {
		return ""
	}
	return *s.RelationshipName
}

// GetRestrictedDelete returns the RestrictedDelete field if it's non-nil, zero value otherwise.
func (s *SObjectFieldMetadata) GetRestrictedDelete() bool {
	if s == nil || s.RestrictedDelete == nil {
		return false
	}
	return *s.RestrictedDelete
}

// GetRestrictedPicklist returns the RestrictedPicklist field if it's non-nil, zero value otherwise.
func (s *SObjectFieldMetadata) GetRestrictedPicklist() bool {
	if s == nil || s.RestrictedPicklist == nil {
		return false
	}
	return *s.RestrictedPicklist
}

// GetScale returns the Scale field if it's non-nil, zero value otherwise.
func (s *SObjectFieldMetadata) GetScale() int {
	if s == nil || s.Scale == nil {
		return 0
	}
	return *s.Scale
}

// GetSoapType returns the SoapType field if it's non-nil, zero value otherwise.
func (s *SObjectFieldMetadata) GetSoapType() string {
	if s == nil || s.SoapType == nil {
		return ""
	}
	return *s.SoapType
}

// GetSortable returns the Sortable field if it's non-nil, zero value otherwise.
func (s *SObjectFieldMetadata) GetSortable() bool {
	if s == nil || s.Sortable == nil {
		return false
	}
	return *s.Sortable
}

// GetType returns the Type field if it's non-nil, zero value otherwise.
func (s *SObjectFieldMetadata) GetType() string {
	if s == nil || s.Type == nil {
		return ""
	}
	return *s.Type
}

// GetUnique returns the Unique field if it's non-nil, zero value otherwise.
func (s *SObjectFieldMetadata) GetUnique() bool {
	if s == nil || s.Unique == nil {
		return false
	}
	return *s.Unique
}

// GetUpdateable returns the Updateable field if it's non-nil, zero value otherwise.
func (s *SObjectFieldMetadata) GetUpdateable() bool {
	if s == nil || s.Updateable == nil {
		return false
	}
	return *s.Updateable
}

// GetWriteRequiresMasterRead returns the WriteRequiresMasterRead field if it's non-nil, zero value otherwise.
func (s *SObjectFieldMetadata) GetWriteRequiresMasterRead() bool {
	if s == nil || s.WriteRequiresMasterRead == nil {
		return false
	}
	return *s.WriteRequiresMasterRead
}

// GetActive returns the Active field if it's non-nil, zero value otherwise.
func (s *SObjectFieldPicklistEntryMetadata) GetActive() bool {
	if s == nil || s.Active == nil {
		return false
	}
	return *s.Active
}

// GetDefaultValue returns the DefaultValue field if it's non-nil, zero value otherwise.
func (s *SObjectFieldPicklistEntryMetadata) GetDefaultValue() bool {
	if s == nil || s.DefaultValue == nil {
		return false
	}
	return *s.DefaultValue
}

// GetLabel returns the Label field if it's non-nil, zero value otherwise.
func (s *SObjectFieldPicklistEntryMetadata) GetLabel() string {
	if s == nil || s.Label == nil {
		return ""
	}
	return *s.Label
}

// GetValidFor returns the ValidFor field if it's non-nil, zero value otherwise.
func (s *SObjectFieldPicklistEntryMetadata) GetValidFor() string {
	if s == nil || s.ValidFor == nil {
		return ""
	}
	return *s.ValidFor
}

// GetValue returns the Value field if it's non-nil, zero value otherwise.
func (s *SObjectFieldPicklistEntryMetadata) GetValue() string {
	if s == nil || s.Value == nil {
		return ""
	}
	return *s.Value
}

// HasActionOverrides checks if SObjectMetadata has any ActionOverrides.
func (s *SObjectMetadata) HasActionOverrides() bool {
	if s == nil || s.ActionOverrides == nil {
		return false
	}
	if len(s.ActionOverrides) == 0 {
		return false
	}
	return true
}

// GetActivateable returns the Activateable field if it's non-nil, zero value otherwise.
func (s *SObjectMetadata) GetActivateable() bool {
	if s == nil || s.Activateable == nil {
		return false
	}
	return *s.Activateable
}

// GetAssociateEntityType returns the AssociateEntityType field if it's non-nil, zero value otherwise.
func (s *SObjectMetadata) GetAssociateEntityType() string {
	if s == nil || s.AssociateEntityType == nil {
		return ""
	}
	return *s.AssociateEntityType
}

// GetAssociateParentEntity returns the AssociateParentEntity field if it's non-nil, zero value otherwise.
func (s *SObjectMetadata) GetAssociateParentEntity() string {
	if s == nil || s.AssociateParentEntity == nil {
		return ""
	}
	return *s.AssociateParentEntity
}

// HasChildRelationships checks if SObjectMetadata has any ChildRelationships.
func (s *SObjectMetadata) HasChildRelationships() bool {
	if s == nil || s.ChildRelationships == nil {
		return false
	}
	if len(s.ChildRelationships) == 0 {
		return false
	}
	return true
}

// GetCompactLayoutable returns the CompactLayoutable field if it's non-nil, zero value otherwise.
func (s *SObjectMetadata) GetCompactLayoutable() bool {
	if s == nil || s.CompactLayoutable == nil {
		return false
	}
	return *s.CompactLayoutable
}

// GetCreateable returns the Createable field if it's non-nil, zero value otherwise.
func (s *SObjectMetadata) GetCreateable() bool {
	if s == nil || s.Createable == nil {
		return false
	}
	return *s.Createable
}

// GetCustom returns the Custom field if it's non-nil, zero value otherwise.
func (s *SObjectMetadata) GetCustom() bool {
	if s == nil || s.Custom == nil {
		return false
	}
	return *s.Custom
}

// GetCustomSetting returns the CustomSetting field if it's non-nil, zero value otherwise.
func (s *SObjectMetadata) GetCustomSetting() bool {
	if s == nil || s.CustomSetting == nil {
		return false
	}
	return *s.CustomSetting
}

// GetDeletable returns the Deletable field if it's non-nil, zero value otherwise.
func (s *SObjectMetadata) GetDeletable() bool {
	if s == nil || s.Deletable == nil {
		return false
	}
	return *s.Deletable
}

// GetDeprecatedAndHidden returns the DeprecatedAndHidden field if it's non-nil, zero value otherwise.
func (s *SObjectMetadata) GetDeprecatedAndHidden() bool {
	if s == nil || s.DeprecatedAndHidden == nil {
		return false
	}
	return *s.DeprecatedAndHidden
}

// GetFeedEnabled returns the FeedEnabled field if it's non-nil, zero value otherwise.
func (s *SObjectMetadata) GetFeedEnabled() bool {
	if s == nil || s.FeedEnabled == nil {
		return false
	}
	return *s.FeedEnabled
}

// HasFields checks if SObjectMetadata has any Fields.
func (s *SObjectMetadata) HasFields() bool {
	if s == nil || s.Fields == nil {
		return false
	}
	if len(s.Fields) == 0 {
		return false
	}
	return true
}

// GetHasSubtypes returns the HasSubtypes field if it's non-nil, zero value otherwise.
func (s *SObjectMetadata) GetHasSubtypes() bool {
	if s == nil || s.HasSubtypes == nil {
		return false
	}
	return *s.HasSubtypes
}

// GetIDEnabled returns the IDEnabled field if it's non-nil, zero value otherwise.
func (s *SObjectMetadata) GetIDEnabled() bool {
	if s == nil || s.IDEnabled == nil {
		return false
	}
	return *s.IDEnabled
}

// GetIsSubtype returns the IsSubtype field if it's non-nil, zero value otherwise.
func (s *SObjectMetadata) GetIsSubtype() bool {
	if s == nil || s.IsSubtype == nil {
		return false
	}
	return *s.IsSubtype
}

// GetKeyPrefix returns the KeyPrefix field if it's non-nil, zero value otherwise.
func (s *SObjectMetadata) GetKeyPrefix() string {
	if s == nil || s.KeyPrefix == nil {
		return ""
	}
	return *s.KeyPrefix
}

// GetLabel returns the Label field if it's non-nil, zero value otherwise.
func (s *SObjectMetadata) GetLabel() string {
	if s == nil || s.Label == nil {
		return ""
	}
	return *s.Label
}

// GetLabelPlural returns the LabelPlural field if it's non-nil, zero value otherwise.
func (s *SObjectMetadata) GetLabelPlural() string {
	if s == nil || s.LabelPlural == nil {
		return ""
	}
	return *s.LabelPlural
}

// GetLayoutable returns the Layoutable field if it's non-nil, zero value otherwise.
func (s *SObjectMetadata) GetLayoutable() bool {
	if s == nil || s.Layoutable == nil {
		return false
	}
	return *s.Layoutable
}

// GetMergeable returns the Mergeable field if it's non-nil, zero value otherwise.
func (s *SObjectMetadata) GetMergeable() bool {
	if s == nil || s.Mergeable == nil {
		return false
	}
	return *s.Mergeable
}

// GetName returns the Name field if it's non-nil, zero value otherwise.
func (s *SObjectMetadata) GetName() string {
	if s == nil || s.Name == nil {
		return ""
	}
	return *s.Name
}

// HasNamedLayoutInfos checks if SObjectMetadata has any NamedLayoutInfos.
func (s *SObjectMetadata) HasNamedLayoutInfos() bool {
	if s == nil || s.NamedLayoutInfos == nil {
		return false
	}
	if len(s.NamedLayoutInfos) == 0 {
		return false
	}
	return true
}

// GetQueryable returns the Queryable field if it's non-nil, zero value otherwise.
func (s *SObjectMetadata) GetQueryable() bool {
	if s == nil || s.Queryable == nil {
		return false
	}
	return *s.Queryable
}

// HasRecordTypeInfos checks if SObjectMetadata has any RecordTypeInfos.
func (s *SObjectMetadata) HasRecordTypeInfos() bool {
	if s == nil || s.RecordTypeInfos == nil {
		return false
	}
	if len(s.RecordTypeInfos) == 0 {
		return false
	}
	return true
}

// GetReplicateable returns the Replicateable field if it's non-nil, zero value otherwise.
func (s *SObjectMetadata) GetReplicateable() bool {
	if s == nil || s.Replicateable == nil {
		return false
	}
	return *s.Replicateable
}

// GetRetrieveable returns the Retrieveable field if it's non-nil, zero value otherwise.
func (s *SObjectMetadata) GetRetrieveable() bool {
	if s == nil || s.Retrieveable == nil {
		return false
	}
	return *s.Retrieveable
}

// GetSearchable returns the Searchable field if it's non-nil, zero value otherwise.
func (s *SObjectMetadata) GetSearchable() bool {
	if s == nil || s.Searchable == nil {
		return false
	}
	return *s.Searchable
}

// GetSearchLayoutable returns the SearchLayoutable field if it's non-nil, zero value otherwise.
func (s *SObjectMetadata) GetSearchLayoutable() bool {
	if s == nil || s.SearchLayoutable == nil {
		return false
	}
	return *s.SearchLayoutable
}

// HasSupportedScopes checks if SObjectMetadata has any SupportedScopes.
func (s *SObjectMetadata) HasSupportedScopes() bool {
	if s == nil || s.SupportedScopes == nil {
		return false
	}
	if len(s.SupportedScopes) == 0 {
		return false
	}
	return true
}

// GetTriggerable returns the Triggerable field if it's non-nil, zero value otherwise.
func (s *SObjectMetadata) GetTriggerable() bool {
	if s == nil || s.Triggerable == nil {
		return false
	}
	return *s.Triggerable
}

// GetUndeletable returns the Undeletable field if it's non-nil, zero value otherwise.
func (s *SObjectMetadata) GetUndeletable() bool {
	if s == nil || s.Undeletable == nil {
		return false
	}
	return *s.Undeletable
}

// GetUpdateable returns the Updateable field if it's non-nil, zero value otherwise.
func (s *SObjectMetadata) GetUpdateable() bool {
	if s == nil || s.Updateable == nil {
		return false
	}
	return *s.Updateable
}

// GetURLDetail returns the URLDetail field if it's non-nil, zero value otherwise.
func (s *SObjectMetadata) GetURLDetail() string {
	if s == nil || s.URLDetail == nil {
		return ""
	}
	return *s.URLDetail
}

// GetURLEdit returns the URLEdit field if it's non-nil, zero value otherwise.
func (s *SObjectMetadata) GetURLEdit() string {
	if s == nil || s.URLEdit == nil {
		return ""
	}
	return *s.URLEdit
}

// GetURLNew returns the URLNew field if it's non-nil, zero value otherwise.
func (s *SObjectMetadata) GetURLNew() string {
	if s == nil || s.URLNew == nil {
		return ""
	}
	return *s.URLNew
}

// GetName returns the Name field if it's non-nil, zero value otherwise.
func (s *SObjectNamedLayoutInfoMetadata) GetName() string {
	if s == nil || s.Name == nil {
		return ""
	}
	return *s.Name
}

// GetAvailable returns the Available field if it's non-nil, zero value otherwise.
func (s *SObjectRecordTypeInfoMetadata) GetAvailable() bool {
	if s == nil || s.Available == nil {
		return false
	}
	return *s.Available
}

// GetDefaultRecordTypeMapping returns the DefaultRecordTypeMapping field if it's non-nil, zero value otherwise.
func (s *SObjectRecordTypeInfoMetadata) GetDefaultRecordTypeMapping() bool {
	if s == nil || s.DefaultRecordTypeMapping == nil {
		return false
	}
	return *s.DefaultRecordTypeMapping
}

// GetDeveloperName returns the DeveloperName field if it's non-nil, zero value otherwise.
func (s *SObjectRecordTypeInfoMetadata) GetDeveloperName() string {
	if s == nil || s.DeveloperName == nil {
		return ""
	}
	return *s.DeveloperName
}

// GetMaster returns the Master field if it's non-nil, zero value otherwise.
func (s *SObjectRecordTypeInfoMetadata) GetMaster() bool {
	if s == nil || s.Master == nil {
		return false
	}
	return *s.Master
}

// GetName returns the Name field if it's non-nil, zero value otherwise.
func (s *SObjectRecordTypeInfoMetadata) GetName() string {
	if s == nil || s.Name == nil {
		return ""
	}
	return *s.Name
}

// GetRecordTypeId returns the RecordTypeId field if it's non-nil, zero value otherwise.
func (s *SObjectRecordTypeInfoMetadata) GetRecordTypeId() string {
	if s == nil || s.RecordTypeId == nil {
		return ""
	}
	return *s.RecordTypeId
}

// GetLabel returns the Label field if it's non-nil, zero value otherwise.
func (s *SObjectScopeInfoInfoMetadata) GetLabel() string {
	if s == nil || s.Label == nil {
		return ""
	}
	return *s.Label
}

// GetName returns the Name field if it's non-nil, zero value otherwise.
func (s *SObjectScopeInfoInfoMetadata) GetName() string {
	if s == nil || s.Name == nil {
		return ""
	}
	return *s.Name
}

// GetAccessToken returns the AccessToken field if it's non-nil, zero value otherwise.
func (t *TokenResponse) GetAccessToken() string {
	if t == nil || t.AccessToken == nil {
		return ""
	}
	return *t.AccessToken
}

// GetID returns the ID field if it's non-nil, zero value otherwise.
func (t *TokenResponse) GetID() string {
	if t == nil || t.ID == nil {
		return ""
	}
	return *t.ID
}

// GetInstanceURL returns the InstanceURL field if it's non-nil, zero value otherwise.
func (t *TokenResponse) GetInstanceURL() string {
	if t == nil || t.InstanceURL == nil {
		return ""
	}
	return *t.InstanceURL
}

// GetIssuedAt returns the IssuedAt field if it's non-nil, zero value otherwise.
func (t *TokenResponse) GetIssuedAt() string {
	if t == nil || t.IssuedAt == nil {
		return ""
	}
	return *t.IssuedAt
}

// GetSignature returns the Signature field if it's non-nil, zero value otherwise.
func (t *TokenResponse) GetSignature() string {
	if t == nil || t.Signature == nil {
		return ""
	}
	return *t.Signature
}

// GetTokenType returns the TokenType field if it's non-nil, zero value otherwise.
func (t *TokenResponse) GetTokenType() string {
	if t == nil || t.TokenType == nil {
		return ""
	}
	return *t.TokenType
}
